server:
  port: 8889

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rafavela/reminder-config.git
          search-paths: config
          default-label: main      
